# Generated by Django 4.2.3 on 2023-07-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchType',
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_type', 'title'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ['start_date'], 'verbose_name': 'ORG', 'verbose_name_plural': 'ORGs'},
        ),
    ]
