# Generated by Django 4.2.3 on 2023-07-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_matchtype_alter_match_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ORG',
        ),
        migrations.AddField(
            model_name='match',
            name='ORGs',
            field=models.ManyToManyField(help_text='Choose all ORGs this Match has appeared in.', to='catalog.org', verbose_name='ORGs'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summary',
            field=models.TextField(help_text='Enter a quick summary of the Match here.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='match',
            name='tags',
            field=models.ManyToManyField(help_text='Choose tags for this book.', to='catalog.tag'),
        ),
    ]
