# Generated by Django 4.2.3 on 2023-07-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_match_org_match_orgs_alter_match_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='description',
            field=models.CharField(default='default', help_text='A short description of this ORG.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='twists',
            field=models.TextField(default='default', help_text='List out all relevant twists of this ORG.', max_length=1000),
            preserve_default=False,
        ),
    ]
