# Generated by Django 4.2.3 on 2023-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_org_description_org_twists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='rules',
            field=models.TextField(help_text='Enter the rules of the Match here.', max_length=30000),
        ),
        migrations.AlterField(
            model_name='match',
            name='tags',
            field=models.ManyToManyField(help_text='Choose tags for this match.', to='catalog.tag'),
        ),
    ]
