# Generated by Django 4.2.3 on 2023-07-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_match_rules_alter_match_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_type', 'name'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(blank=True, choices=[('DM', 'Death Match'), ('MM', 'Main Match')], max_length=2),
        ),
    ]
