# Generated by Django 4.2.3 on 2023-07-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_match_options_rename_title_match_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
