# Generated by Django 4.2.3 on 2023-07-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_org_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_type', 'name'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
