# Generated by Django 4.2.3 on 2023-07-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_match_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='num_players',
        ),
        migrations.AddField(
            model_name='match',
            name='max_players',
            field=models.IntegerField(blank=True, help_text='Maximum number of players that can play this match. Leave empty if num_players is not a range.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='min_players',
            field=models.IntegerField(default=2, help_text='Minimum number of players needed to play this match.'),
            preserve_default=False,
        ),
    ]
