# Generated by Django 4.2.3 on 2023-07-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_match_num_players_match_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Choose tags for this match.', to='catalog.tag'),
        ),
    ]
