# Generated by Django 4.2.3 on 2023-07-18 23:46

from django.db import migrations

def forward(apps, schema_editor):
    Match = apps.get_model("catalog", "Match")
    for match in Match.objects.all():
        match.designers.add(match.designer)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_match_designers_alter_match_match_type_and_more'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]


