# Generated by Django 4.2.3 on 2023-07-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_designer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designer',
            options={},
        ),
        migrations.AlterField(
            model_name='match',
            name='designers',
            field=models.ManyToManyField(to='catalog.designer', verbose_name='Designer'),
        ),
    ]
