# Generated by Django 4.2.7 on 2023-12-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_match_designers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
