# Generated by Django 4.2.7 on 2024-04-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_designer_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='see_also',
            field=models.ManyToManyField(help_text='Note games that are inspired by or are similar to this game.', to='catalog.match', verbose_name='See Also'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a description for the tag.', max_length=1000, null=True),
        ),
    ]
