# Generated by Django 4.2.7 on 2024-04-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_match_see_also_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='see_also',
            field=models.ManyToManyField(blank=True, help_text='Note games that are inspired by or are similar to this game.', to='catalog.match', verbose_name='See Also'),
        ),
    ]
