# Generated by Django 4.2.7 on 2024-09-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_match_see_also'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the name of this award (e.g. 'Most Fun MM').", max_length=200)),
                ('description', models.CharField(help_text='Enter the description of this award.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='YearAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024)),
                ('award', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.award')),
            ],
        ),
    ]
