# Generated by Django 4.2.7 on 2024-09-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_award_yearaward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='match',
            name='awards',
            field=models.ManyToManyField(blank=True, help_text='Choose all awards this design has won.', to='catalog.yearaward'),
        ),
    ]
