# Generated by Django 4.2.15 on 2024-09-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_award_options_match_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='rules',
            field=models.TextField(help_text='Enter the rules of the Match here.', max_length=50000),
        ),
    ]
