# Generated by Django 5.1.3 on 2024-11-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_yearaward_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['name', 'match_type', 'min_players'], name='catalog_mat_name_b0f7af_idx'),
        ),
    ]
