# Generated by Django 5.1.3 on 2025-01-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_match_catalog_mat_name_b0f7af_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='award',
            name='priority',
            field=models.IntegerField(default=100, help_text='Priority value for awards ordering in view.'),
        ),
        migrations.AlterField(
            model_name='yearaward',
            name='year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025),
        ),
    ]
